apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- service_account.yaml
images:
- name: controller
  newName: infra-provider-gcp
  newTag: latest
configMapGenerator:
- files:
  - config.yaml
  name: config
  options:
    disableNameSuffixHash: true
