---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upstream-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.datumapis.com
  resources:
  - networkcontexts
  - networks
  - subnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.datumapis.com
  resources:
  - networkcontexts/finalizers
  - networks/finalizers
  - subnets/finalizers
  verbs:
  - update
- apiGroups:
  - networking.datumapis.com
  resources:
  - networkcontexts/status
  - subnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.datumapis.com
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.datumapis.com
  resources:
  - workloads/finalizers
  verbs:
  - update
