# This rule is not used by the project infra-provider-gcp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infra.datumapis.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infra-provider-gcp
    app.kubernetes.io/managed-by: kustomize
  name: downstreamworkloaddeployment-admin-role
rules:
- apiGroups:
  - infra.datumapis.com
  resources:
  - downstreamworkloaddeployments
  verbs:
  - '*'
- apiGroups:
  - infra.datumapis.com
  resources:
  - downstreamworkloaddeployments/status
  verbs:
  - get
