---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - compute.cnrm.cloud.google.com
  resources:
  - computenetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.cnrm.cloud.google.com
  resources:
  - computenetworks/status
  verbs:
  - get
- apiGroups:
  - compute.datumapis.com
  resources:
  - networkcontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - networkcontexts/finalizers
  verbs:
  - update
- apiGroups:
  - compute.datumapis.com
  resources:
  - networkcontexts/status
  verbs:
  - get
  - patch
  - update
